module.exports = {
  android: {
    edgeToEdgeEnabled: true,
    adaptiveIcon: {
      foregroundImage: "./assets/images/icon.png",
      // Matches the icon artwork's own background so the launcher mask has no seam.
      backgroundColor: "#2E89B7",
    },
    package: "org.improvingyouthjustice.reentryroadmap",
    versionCode: 4,
    allowBackup: undefined,
    permissions: undefined,
    blockedPermissions: undefined,
  },
  assetBundlePatterns: ["**/*"],
  experiments: { typedRoutes: true, tsconfigPaths: true },
  extra: undefined,

  icon: "./assets/images/icon.png",
  ios: {
    supportsTablet: true,
    bundleIdentifier: "org.improvingyouthjustice.reentryroadmap",
    buildNumber: "4",
    usesAppleSignIn: false,
    requireFullScreen: false,
    associatedDomains: undefined,
    appStoreUrl: undefined,
    isTabletOnly: undefined,
    infoPlist: {
      UIStatusBarStyle: "UIStatusBarStyleLightContent",
      NSCameraUsageDescription: undefined,
      NSMicrophoneUsageDescription: undefined,
      NSPhotoLibraryUsageDescription: undefined,
      NSPhotoLibraryAddUsageDescription: undefined,
      NSLocationWhenInUseUsageDescription: undefined,
      NSLocationAlwaysUsageDescription: undefined,
      NSContactsUsageDescription: undefined,
      NSCalendarsUsageDescription: undefined,
      NSRemindersUsageDescription: undefined,
      NSMotionUsageDescription: undefined,
      NSFaceIDUsageDescription: undefined,
      NSSpeechRecognitionUsageDescription: undefined,
      NSBluetoothPeripheralUsageDescription: undefined,
      NSAppleMusicUsageDescription: undefined,
      NSUserTrackingUsageDescription: undefined,
    },
    privacyManifests: undefined,
    bitcode: undefined,
  },
  name: "NexPath",
  orientation: "portrait",
  plugins: [
    "expo-font",
    "expo-asset",
    "expo-secure-store",
    "expo-notifications",
    "expo-video",
    "expo-web-browser",

    [
      "expo-router",
      {
        origin: "https://9eac55506b.sandbox.draftbit.dev:5101",
        headOrigin: "https://9eac55506b.sandbox.draftbit.dev:5100",
      },
    ],
    ["./plugins/draftbit-auto-launch-url-plugin"],
  ],

  scheme: "nexpath",
  slug: "nexpath",
  splash: {
    image: "./assets/images/splash.png",
    // contain keeps the lockup undistorted; the backdrop is the artwork's own blue,
    // so the letterboxing on taller screens is invisible.
    resizeMode: "contain",
    backgroundColor: "#2E89B7",
  },
  userInterfaceStyle: "light",
  version: "1.10.4",
  web: {
    bundler: "metro",
    output: "single",
    favicon: "./assets/images/icon.png",
    themeColor: undefined,
    name: undefined,
    shortName: undefined,
    lang: undefined,
    backgroundColor: undefined,
    description: undefined,
    orientation: undefined,
    startUrl: undefined,
  },
  platforms: ["ios", "android", "web"],
  description: undefined,
  locales: undefined,
  jsEngine: undefined,
  notification: {
    icon: undefined,
    color: undefined,
    iosDisplayInForeground: false,
    androidMode: "default",
    androidCollapsedTitle: undefined,
  },
};
